// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;

namespace AvidScript;

public enum AvidStateMode
{
    Compatible = 0,
    Explicit = 1,
}

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class AvidStateContractAttribute : Attribute
{
    public AvidStateContractAttribute(AvidStateMode mode = AvidStateMode.Compatible)
    {
        Mode = mode;
    }

    public AvidStateMode Mode { get; }
    public int Version { get; set; } = 1;
}

[AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
public sealed class AvidPersistAttribute : Attribute
{
}

[AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
public sealed class AvidTransientAttribute : Attribute
{
}

[AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = true)]
public sealed class AvidStateAliasAttribute : Attribute
{
    public AvidStateAliasAttribute(string formerName)
    {
        FormerName = formerName;
    }

    public string FormerName { get; }
}

internal static class AvidScriptBindingPackage
{
    internal const string PackageName = "avidscript.engine.fname.facade";
    internal const string PackageHash = "219425b03b7d209d71764c89cb3d30d6c8ac4c2b02a563e586e456e95d5084a2";
    internal const string DescriptorHash = "42469630f7273430ac0111af63324f107b94ff20dec1042dde1582a144552ba8";
}

[StructLayout(LayoutKind.Sequential)]
public readonly struct FVector
{
    public readonly float X;
    public readonly float Y;
    public readonly float Z;

    public FVector(float x, float y, float z)
    {
        X = x;
        Y = y;
        Z = z;
    }

    public static FVector Zero => new(0.0f, 0.0f, 0.0f);
    public static FVector operator +(FVector left, FVector right)
        => new(left.X + right.X, left.Y + right.Y, left.Z + right.Z);
}

[StructLayout(LayoutKind.Sequential)]
public readonly struct InputEvent
{
    public readonly int ActionId;
    public readonly int TriggerEvent;
    public readonly FVector Value;

    internal InputEvent(int actionId, int triggerEvent, FVector value)
    {
        ActionId = actionId;
        TriggerEvent = triggerEvent;
        Value = value;
    }
}

[StructLayout(LayoutKind.Sequential)]
internal readonly struct FAvidScriptObjectHandle
{
    internal readonly int Slot;
    internal readonly int Generation;

    internal FAvidScriptObjectHandle(int slot, int generation)
    {
        Slot = slot;
        Generation = generation;
    }
}

[StructLayout(LayoutKind.Sequential)]
public readonly struct AActor
{
    private readonly int Slot;
    private readonly int Generation;

    internal AActor(int slot, int generation)
    {
        Slot = slot;
        Generation = generation;
    }

    internal int AvidScriptSlot => Slot;
    internal int AvidScriptGeneration => Generation;
    public bool IsNull => Slot == 0 && Generation == 0;
    public bool HasHandle => Slot > 0 && Generation > 0;
    public bool IsValid => Slot > 0 && Generation > 0;

    public bool ActorHasTag(string Tag)
    {
        int __returnValue;
        _ = AvidScriptNative.Invoke0000(this.Slot, this.Generation, Tag, out __returnValue);
        return __returnValue != 0;
    }
}

public static class UE
{
    public static AActor Self => new(AvidScriptRuntimeNative.OwnerGetSlot(), AvidScriptRuntimeNative.OwnerGetGeneration());
}

internal static class AvidScriptRuntimeNative
{
    [DllImport("env", EntryPoint = "owner_get_slot")]
    internal static extern int OwnerGetSlot();

    [DllImport("env", EntryPoint = "owner_get_generation")]
    internal static extern int OwnerGetGeneration();
}

internal static class AvidScriptNative
{
    [DllImport("avidscript", EntryPoint = "avid_ue_31cc75e0bdf4ab1e")]
    internal static extern int Invoke0000(int selfSlot, int selfGeneration, string p0, out int returnValue);
}
