// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;

namespace AvidScript;

[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
public sealed class AvidExportAttribute : Attribute
{
    public AvidExportAttribute(string entryPoint)
    {
        EntryPoint = entryPoint;
    }

    public string EntryPoint { get; }
}

[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
public sealed class AvidContinuationAttribute : Attribute
{
    public AvidContinuationAttribute(int callbackId)
    {
        CallbackId = callbackId;
    }

    public int CallbackId { get; }
}

public readonly struct AvidContinuation
{
    private readonly long Token;

    internal AvidContinuation(long token)
    {
        Token = token;
    }

    public bool IsValid => Token != 0;
    public bool Cancel() => AvidScriptRuntimeNative.ContinuationCancel(Token) != 0;
}

public static class AvidContinuations
{
    public static AvidContinuation Delay(float delaySeconds, int callbackId)
        => new(AvidScriptRuntimeNative.ContinuationDelay(delaySeconds, callbackId));

    public static AvidContinuation NextTick(int callbackId)
        => new(AvidScriptRuntimeNative.ContinuationDelay(0.0f, callbackId));
}

public enum AvidStateMode
{
    Compatible = 0,
    Explicit = 1,
}

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class AvidStateContractAttribute : Attribute
{
    public AvidStateContractAttribute(AvidStateMode mode = AvidStateMode.Compatible)
    {
        Mode = mode;
    }

    public AvidStateMode Mode { get; }
    public int Version { get; set; } = 1;
}

[AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
public sealed class AvidPersistAttribute : Attribute
{
}

[AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
public sealed class AvidTransientAttribute : Attribute
{
}

[AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = true)]
public sealed class AvidStateAliasAttribute : Attribute
{
    public AvidStateAliasAttribute(string formerName)
    {
        FormerName = formerName;
    }

    public string FormerName { get; }
}

internal static class AvidScriptBindingPackage
{
    internal const string PackageName = "avidscript.engine.fname.facade";
    internal const string PackageHash = "67898628adbbab5a59e93f98660877e0aca252bf3c2e167ed3dde16ab31ef2a4";
    internal const string DescriptorHash = "285336c1bc133cd0fa72f2a7ebc96567d82eaea9c0e86a6f5527e61e76c7b92b";
}

[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
internal sealed class AvidScriptDataLaneAttribute : Attribute
{
    internal AvidScriptDataLaneAttribute(string optimizationClass, int bindingOrdinal)
    {
        OptimizationClass = optimizationClass;
        BindingOrdinal = bindingOrdinal;
    }

    internal string OptimizationClass { get; }
    internal int BindingOrdinal { get; }
}

[StructLayout(LayoutKind.Sequential)]
public readonly struct FVector
{
    public readonly float X;
    public readonly float Y;
    public readonly float Z;

    public FVector(float x, float y, float z)
    {
        X = x;
        Y = y;
        Z = z;
    }

    public static FVector Zero => new(0.0f, 0.0f, 0.0f);
    public static FVector operator +(FVector left, FVector right)
        => new(left.X + right.X, left.Y + right.Y, left.Z + right.Z);
}

[StructLayout(LayoutKind.Sequential)]
public readonly struct InputEvent
{
    public readonly int ActionId;
    public readonly int TriggerEvent;
    public readonly FVector Value;

    internal InputEvent(int actionId, int triggerEvent, FVector value)
    {
        ActionId = actionId;
        TriggerEvent = triggerEvent;
        Value = value;
    }
}

[StructLayout(LayoutKind.Sequential)]
internal readonly struct FAvidScriptObjectHandle
{
    internal readonly int Slot;
    internal readonly int Generation;

    internal FAvidScriptObjectHandle(int slot, int generation)
    {
        Slot = slot;
        Generation = generation;
    }
}

[StructLayout(LayoutKind.Sequential)]
public readonly struct UObject
{
    internal readonly int Slot;
    internal readonly int Generation;

    internal UObject(int slot, int generation)
    {
        Slot = slot;
        Generation = generation;
    }

    internal int AvidScriptSlot => Slot;
    internal int AvidScriptGeneration => Generation;
    public bool IsNull => Slot == 0 && Generation == 0;
    public bool HasHandle => Slot > 0 && Generation > 0;
    public bool IsValid => Slot > 0 && Generation > 0;
}

[StructLayout(LayoutKind.Sequential)]
public readonly struct AActor
{
    internal readonly int Slot;
    internal readonly int Generation;

    internal AActor(int slot, int generation)
    {
        Slot = slot;
        Generation = generation;
    }

    internal int AvidScriptSlot => Slot;
    internal int AvidScriptGeneration => Generation;
    public bool IsNull => Slot == 0 && Generation == 0;
    public bool HasHandle => Slot > 0 && Generation > 0;
    public bool IsValid => Slot > 0 && Generation > 0;

    public static implicit operator UObject(AActor value)
    {
        return new(value.Slot, value.Generation);
    }

    public static AActor TryCast(UObject value)
    {
        if (AvidScriptNative.ObjectTypeIsA(value.Slot, value.Generation, 1) != 0)
        {
            return new(value.Slot, value.Generation);
        }
        return default;
    }

    public bool ActorHasTag(string Tag)
    {
        int __returnValue;
        _ = AvidScriptNative.Invoke0000(this.Slot, this.Generation, Tag, out __returnValue);
        return __returnValue != 0;
    }
}

public static class UE
{
    public static AActor Self
    {
        get
        {
            long packedHandle = OwnerGetHandle();
            return new((int)packedHandle, (int)(packedHandle >> 32));
        }
    }
    public static int SetTimer(float delaySeconds, int callbackId) => AvidScriptRuntimeNative.TimerSetOnce(delaySeconds, callbackId);
    public static bool CancelTimer(int timerHandle) => AvidScriptRuntimeNative.TimerCancel(timerHandle) != 0;

    [DllImport("avidscript", EntryPoint = "avid_owner_get_handle")]
    private static extern long OwnerGetHandle();
}

internal static class AvidScriptRuntimeNative
{
    [DllImport("env", EntryPoint = "continuation_delay")]
    internal static extern long ContinuationDelay(float delaySeconds, int callbackId);

    [DllImport("env", EntryPoint = "continuation_cancel")]
    internal static extern int ContinuationCancel(long continuationToken);

    [DllImport("env", EntryPoint = "timer_set_once")]
    internal static extern int TimerSetOnce(float delaySeconds, int callbackId);

    [DllImport("env", EntryPoint = "timer_cancel")]
    internal static extern int TimerCancel(int timerHandle);
}

internal static class AvidScriptNative
{
    [DllImport("avidscript", EntryPoint = "avid_ue_31cc75e0bdf4ab1e")]
    internal static extern int Invoke0000(int selfSlot, int selfGeneration, string p0, out int returnValue);

    [DllImport("avidscript", EntryPoint = "avid_object_type_is_a")]
    internal static extern int ObjectTypeIsA(int slot, int generation, int targetOrdinal);
}
