import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const path = process.argv[2];
assert.ok(path, 'Pass the local-functions.wasm emitted by CSharpGuestLocalFunctionTests.');
const bytes = readFileSync(path);
assert.ok(WebAssembly.validate(bytes), 'The generated bytes must be a valid WASM module.');
const { instance } = await WebAssembly.instantiate(bytes, {});
const { run, branch } = instance.exports;
assert.equal(typeof run, 'function');
assert.equal(typeof branch, 'function');
let cases = 0;
// Repeat calls to detect ref/out scratch storage leaking between invocations.
for (let round = 0; round < 3; ++round) {
    for (let value = -2; value <= 64; ++value) {
        const sum = value > 0 ? value * (value + 1) : 0;
        assert.equal(run(value), 2 * sum + 7, `run(${value}), round ${round}`);
        assert.equal(branch(value), value > 0 ? 11 : 29, `branch(${value}), round ${round}`);
        cases += 2;
    }
}
console.log(`AvidScript.LocalFunctions.WasmExecution: ${cases}/${cases} passed`);
