using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AvidScript.CSharpSemantic;

namespace AvidScript.UeTypeGenerator;

internal static class UhtShellRenderer
{
    public const string HeaderPath = "Public/AvidScriptGeneratedTypes.h";
    public const string SourcePath = "Private/AvidScriptGeneratedTypes.cpp";

    public static string RenderHeader(string moduleName, IReadOnlyList<UeTypeManifestEntry> types)
    {
        StringBuilder output = new();
        output.AppendLine("// Generated by AvidScript.UeTypeGenerator. Do not edit.");
        output.AppendLine("#pragma once");
        output.AppendLine();
        output.AppendLine("#include \"CoreMinimal.h\"");
        output.AppendLine("#include \"Components/ActorComponent.h\"");
        output.AppendLine("#include \"GameFramework/Actor.h\"");
        output.AppendLine("#include \"Subsystems/GameInstanceSubsystem.h\"");
        output.AppendLine("#include \"Subsystems/WorldSubsystem.h\"");
        output.AppendLine("#include \"AvidScriptGeneratedTypes.generated.h\"");
        output.AppendLine();

        string apiMacro = moduleName.ToUpperInvariant() + "_API";
        foreach (UeTypeManifestEntry type in TopologicalOrder(types))
        {
            output.Append("UCLASS(").Append(RenderClassFlags(type.Flags)).AppendLine(")");
            output.Append("class ").Append(apiMacro).Append(' ').Append(type.CppName)
                .Append(" : public ").AppendLine(type.BaseCppName);
            output.AppendLine("{");
            output.AppendLine("    GENERATED_BODY()");
            output.AppendLine();
            output.AppendLine("public:");
            if (NeedsConstructor(type))
            {
                output.Append("    ").Append(type.CppName).AppendLine("();");
                output.AppendLine();
            }
            foreach (UePropertyManifestEntry property in type.Properties)
            {
                output.Append("    UPROPERTY(").Append(RenderPropertyFlags(property)).AppendLine(")");
                output.Append("    ").Append(property.CppType).Append(' ').Append(property.Name).AppendLine(";");
                output.AppendLine();
            }
            foreach (UeFunctionManifestEntry function in type.Functions.Where(function =>
                !function.Flags.Contains("lifecycle")))
            {
                AppendFunctionDeclaration(output, function);
            }
            if (type.Properties.Any(property => property.Flags.Contains("replicated")))
            {
                output.AppendLine("    virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;");
                output.AppendLine();
            }

            UeFunctionManifestEntry[] lifecycleFunctions = type.Functions
                .Where(function => function.Flags.Contains("lifecycle"))
                .ToArray();
            string[] hostLifecycleNames = GetHostLifecycleNames(type.Kind);
            if (lifecycleFunctions.Length > 0 || hostLifecycleNames.Length > 0
                || type.Kind == "world_subsystem")
            {
                output.AppendLine("protected:");
                foreach (UeFunctionManifestEntry function in lifecycleFunctions)
                {
                    output.Append("    ").AppendLine(RenderLifecycleDeclaration(type.Kind, function));
                }
                foreach (string lifecycleName in hostLifecycleNames.Where(name =>
                    !lifecycleFunctions.Any(function => function.Name == name)))
                {
                    output.Append("    ").AppendLine(RenderLifecycleDeclaration(type.Kind, lifecycleName));
                }
                if (type.Kind == "world_subsystem")
                {
                    output.AppendLine("    virtual TStatId GetStatId() const override;");
                }
                output.AppendLine();
            }
            output.AppendLine("};");
            output.AppendLine();
        }
        return Normalize(output);
    }

    public static string RenderSource(IReadOnlyList<UeTypeManifestEntry> types)
    {
        StringBuilder output = new();
        output.AppendLine("// Generated by AvidScript.UeTypeGenerator. Do not edit.");
        output.AppendLine("#include \"AvidScriptGeneratedTypes.h\"");
        output.AppendLine();
        output.AppendLine("#include \"Net/UnrealNetwork.h\"");
        output.AppendLine("#include \"ScriptTypes/AvidScriptGeneratedTypeDispatcher.h\"");
        output.AppendLine("#include \"ScriptTypes/AvidScriptGeneratedTypeRuntimeHost.h\"");
        output.AppendLine("#if WITH_DEV_AUTOMATION_TESTS");
        output.AppendLine("#include \"Misc/AutomationTest.h\"");
        output.AppendLine("#include \"UObject/UnrealType.h\"");
        output.AppendLine("#endif");
        output.AppendLine();
        output.AppendLine("DEFINE_LOG_CATEGORY_STATIC(LogAvidScriptGeneratedTypes, Log, All);");
        output.AppendLine();

        foreach (UeTypeManifestEntry type in TopologicalOrder(types))
        {
            UePropertyManifestEntry[] initializedProperties = type.Properties
                .Where(property => property.Initializer is not null)
                .ToArray();
            if (NeedsConstructor(type))
            {
                output.Append(type.CppName).Append("::").Append(type.CppName).AppendLine("()");
                output.AppendLine("{");
                foreach (UePropertyManifestEntry property in initializedProperties)
                {
                    output.Append("    ").Append(property.Name).Append(" = ")
                        .Append(RenderInitializer(property.Initializer!)).AppendLine(";");
                }
                if (HasScheduledTick(type))
                {
                    string tickMember = type.Kind == "actor" ? "PrimaryActorTick" : "PrimaryComponentTick";
                    output.Append("    ").Append(tickMember).AppendLine(".bCanEverTick = true;");
                    output.Append("    ").Append(tickMember).AppendLine(".bStartWithTickEnabled = true;");
                }
                if (HasNetworkContract(type))
                {
                    output.AppendLine(type.Kind == "actor"
                        ? "    bReplicates = true;"
                        : "    SetIsReplicatedByDefault(true);");
                }
                output.AppendLine("}");
                output.AppendLine();
            }
            foreach (UeFunctionManifestEntry function in type.Functions)
            {
                if (function.Flags.Contains("blueprint_implementable_event"))
                {
                    continue;
                }
                AppendFunctionDefinition(output, type, function);
            }
            foreach (string lifecycleName in GetHostLifecycleNames(type.Kind).Where(name =>
                !type.Functions.Any(function =>
                    function.Flags.Contains("lifecycle") && function.Name == name)))
            {
                AppendHostLifecycleDefinition(output, type, lifecycleName);
            }
            if (type.Properties.Any(property => property.Flags.Contains("replicated")))
            {
                output.Append("void ").Append(type.CppName)
                    .AppendLine("::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const");
                output.AppendLine("{");
                output.AppendLine("    Super::GetLifetimeReplicatedProps(OutLifetimeProps);");
                foreach (UePropertyManifestEntry property in type.Properties.Where(property =>
                    property.Flags.Contains("replicated")))
                {
                    output.Append("    DOREPLIFETIME(").Append(type.CppName).Append(", ")
                        .Append(property.Name).AppendLine(");");
                }
                output.AppendLine("}");
                output.AppendLine();
            }
            if (type.Kind == "world_subsystem")
            {
                output.Append("TStatId ").Append(type.CppName).AppendLine("::GetStatId() const");
                output.AppendLine("{");
                output.Append("    RETURN_QUICK_DECLARE_CYCLE_STAT(").Append(type.CppName)
                    .AppendLine(", STATGROUP_Tickables);");
                output.AppendLine("}");
                output.AppendLine();
            }
        }
        AppendReflectionTest(output, types);
        return Normalize(output);
    }

    private static void AppendReflectionTest(
        StringBuilder output,
        IReadOnlyList<UeTypeManifestEntry> types)
    {
        if (types.Count == 0)
        {
            return;
        }
        output.AppendLine("#if WITH_DEV_AUTOMATION_TESTS");
        output.AppendLine("IMPLEMENT_SIMPLE_AUTOMATION_TEST(");
        output.AppendLine("    FAvidScriptGeneratedTypeReflectionTest,");
        output.AppendLine("    \"AvidScript.GeneratedTypes.Reflection\",");
        output.AppendLine("    EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)");
        output.AppendLine();
        output.AppendLine("bool FAvidScriptGeneratedTypeReflectionTest::RunTest(const FString& Parameters)");
        output.AppendLine("{");
        output.AppendLine("    static_cast<void>(Parameters);");
        foreach (UeTypeManifestEntry type in types.OrderBy(type => type.TypeOrdinal))
        {
            string label = Escape(type.EngineName);
            output.Append("    UClass* ").Append(type.CppName).Append("Class = ")
                .Append(type.CppName).AppendLine("::StaticClass();");
            output.Append("    TestNotNull(TEXT(\"").Append(label).Append(" StaticClass exists\"), ")
                .Append(type.CppName).AppendLine("Class);");
            output.Append("    TestEqual(TEXT(\"").Append(label).Append(" reflection name\"), ")
                .Append(type.CppName).Append("Class->GetName(), FString(TEXT(\"")
                .Append(label).AppendLine("\")));");
            output.Append("    TestTrue(TEXT(\"").Append(label).Append(" direct native base\"), ")
                .Append(type.CppName).Append("Class->GetSuperClass() == ")
                .Append(type.BaseCppName).AppendLine("::StaticClass());");
            foreach (UePropertyManifestEntry property in type.Properties)
            {
                output.Append("    TestNotNull(TEXT(\"").Append(label).Append('.')
                    .Append(Escape(property.Name)).Append(" property exists\"), FindFProperty<FProperty>(")
                    .Append(type.CppName).Append("Class, TEXT(\"").Append(Escape(property.Name))
                    .AppendLine("\")));");
            }
            foreach (UeFunctionManifestEntry function in type.Functions.Where(function =>
                !function.Flags.Contains("lifecycle")))
            {
                output.Append("    TestNotNull(TEXT(\"").Append(label).Append('.')
                    .Append(Escape(function.Name)).Append(" function exists\"), ")
                    .Append(type.CppName).Append("Class->FindFunctionByName(TEXT(\"")
                    .Append(Escape(function.Name)).AppendLine("\")));");
            }
            output.AppendLine();
        }
        output.AppendLine("    return true;");
        output.AppendLine("}");
        output.AppendLine("#endif");
        output.AppendLine();
    }

    private static void AppendFunctionDeclaration(StringBuilder output, UeFunctionManifestEntry function)
    {
        bool isOverride = function.Flags.Contains("override");
        bool generatedImplementation = IsGeneratedImplementation(function);
        if (!isOverride)
        {
            output.Append("    UFUNCTION(").Append(RenderFunctionFlags(function)).AppendLine(")");
        }
        if (generatedImplementation)
        {
            if (!isOverride)
            {
                output.Append("    ").Append(RenderSignature(function, function.Name, false)).AppendLine(";");
            }
            output.Append("    virtual ").Append(RenderSignature(function, function.Name + "_Implementation", false))
                .Append(isOverride ? " override;" : ";").AppendLine();
        }
        else
        {
            output.Append("    virtual ").Append(RenderSignature(function, function.Name, false));
            if (isOverride)
            {
                output.Append(" override");
            }
            output.AppendLine(";");
        }
        output.AppendLine();
    }

    private static void AppendFunctionDefinition(
        StringBuilder output,
        UeTypeManifestEntry type,
        UeFunctionManifestEntry function)
    {
        if (function.Flags.Contains("lifecycle"))
        {
            AppendLifecycleDefinition(output, type, function);
            return;
        }

        string nativeName = IsGeneratedImplementation(function)
            ? function.Name + "_Implementation"
            : function.Name;
        output.Append(function.ReturnCppType).Append(' ').Append(type.CppName).Append("::")
            .Append(nativeName).Append('(').Append(RenderParameters(function.Parameters)).AppendLine(")");
        output.AppendLine("{");
        AppendDispatchBody(output, type, function, function.Parameters.Select(parameter => parameter.Name).ToArray());
        output.AppendLine("}");
        output.AppendLine();
    }

    private static void AppendLifecycleDefinition(
        StringBuilder output,
        UeTypeManifestEntry type,
        UeFunctionManifestEntry function)
    {
        string definition = RenderLifecycleDefinition(type, function);
        output.AppendLine(definition);
        output.AppendLine("{");
        bool dispatchBeforeSuper = function.Name is "EndPlay" or "Deinitialize";
        if (!dispatchBeforeSuper)
        {
            output.Append("    ").AppendLine(RenderSuperCall(type.Kind, function));
        }
        if (IsActivationLifecycle(function.Name))
        {
            AppendBeginInstance(output, type);
        }
        string[] arguments = function.Name == "Tick"
            ? new[] { type.Kind == "actor_component" ? "DeltaTime" : "DeltaSeconds" }
            : Array.Empty<string>();
        AppendDispatchBody(output, type, function, arguments);
        if (IsDeactivationLifecycle(function.Name))
        {
            AppendEndInstance(output);
        }
        if (dispatchBeforeSuper)
        {
            output.Append("    ").AppendLine(RenderSuperCall(type.Kind, function));
        }
        output.AppendLine("}");
        output.AppendLine();
    }

    private static void AppendHostLifecycleDefinition(
        StringBuilder output,
        UeTypeManifestEntry type,
        string lifecycleName)
    {
        output.Append(RenderLifecycleDefinition(type, lifecycleName)).AppendLine();
        output.AppendLine("{");
        if (IsActivationLifecycle(lifecycleName))
        {
            output.Append("    ").AppendLine(RenderSuperCall(type.Kind, lifecycleName));
            AppendBeginInstance(output, type);
        }
        else
        {
            AppendEndInstance(output);
            output.Append("    ").AppendLine(RenderSuperCall(type.Kind, lifecycleName));
        }
        output.AppendLine("}");
        output.AppendLine();
    }

    private static void AppendBeginInstance(StringBuilder output, UeTypeManifestEntry type)
    {
        output.AppendLine("    FString AvidScriptRuntimeError;");
        output.AppendLine("    if (!FAvidScriptGeneratedTypeRuntimeHost::Get().BeginInstance(");
        output.AppendLine("        *this,");
        output.Append("        ").Append(type.TypeOrdinal).AppendLine("u,");
        output.AppendLine("        AvidScriptRuntimeError))");
        output.AppendLine("    {");
        output.Append("        UE_LOG(LogAvidScriptGeneratedTypes, Error, TEXT(\"Failed to activate ")
            .Append(Escape(type.EngineName))
            .AppendLine(": %s\"), *AvidScriptRuntimeError);");
        output.AppendLine("        return;");
        output.AppendLine("    }");
    }

    private static void AppendEndInstance(StringBuilder output)
    {
        output.AppendLine("    FString AvidScriptRuntimeError;");
        output.AppendLine("    if (!FAvidScriptGeneratedTypeRuntimeHost::Get().EndInstance(*this, AvidScriptRuntimeError))");
        output.AppendLine("    {");
        output.AppendLine("        UE_LOG(LogAvidScriptGeneratedTypes, Warning, TEXT(\"Failed to stop generated script instance: %s\"), *AvidScriptRuntimeError);");
        output.AppendLine("    }");
    }

    private static void AppendDispatchBody(
        StringBuilder output,
        UeTypeManifestEntry type,
        UeFunctionManifestEntry function,
        IReadOnlyList<string> arguments)
    {
        if (arguments.Count > 0)
        {
            output.AppendLine("    FAvidScriptGeneratedCallArgument Arguments[] =");
            output.AppendLine("    {");
            foreach (string argument in arguments)
            {
                output.Append("        { &").Append(argument).AppendLine(" },");
            }
            output.AppendLine("    };");
        }
        if (function.ReturnCppType != "void")
        {
            output.Append("    ").Append(function.ReturnCppType).AppendLine(" Result{};");
        }
        output.AppendLine("    FAvidScriptGeneratedTypeDispatcher::Invoke(");
        output.AppendLine("        this,");
        output.Append("        ").Append(type.TypeOrdinal).AppendLine("u,");
        output.Append("        ").Append(function.MemberOrdinal).AppendLine("u,");
        output.Append("        ").Append(arguments.Count == 0
            ? "TConstArrayView<FAvidScriptGeneratedCallArgument>()"
            : "MakeArrayView(Arguments)").AppendLine(",");
        output.Append("        ").Append(function.ReturnCppType == "void" ? "nullptr" : "&Result").AppendLine(");");
        if (function.ReturnCppType != "void")
        {
            output.AppendLine("    return Result;");
        }
    }

    private static string RenderLifecycleDeclaration(string kind, UeFunctionManifestEntry function)
    {
        return RenderLifecycleDeclaration(kind, function.Name);
    }

    private static string RenderLifecycleDeclaration(string kind, string lifecycleName)
    {
        return "virtual " + RenderLifecycleSignature(kind, lifecycleName) + " override;";
    }

    private static string RenderLifecycleDefinition(UeTypeManifestEntry type, UeFunctionManifestEntry function)
    {
        return RenderLifecycleDefinition(type, function.Name);
    }

    private static string RenderLifecycleDefinition(UeTypeManifestEntry type, string lifecycleName)
    {
        string signature = RenderLifecycleSignature(type.Kind, lifecycleName);
        int nameOffset = signature.IndexOf(lifecycleName, StringComparison.Ordinal);
        return signature.Insert(nameOffset, type.CppName + "::");
    }

    private static string RenderLifecycleSignature(string kind, string lifecycleName)
    {
        return (kind, lifecycleName) switch
        {
            ("actor", "BeginPlay") or ("actor_component", "BeginPlay") => "void BeginPlay()",
            ("actor", "Tick") => "void Tick(float DeltaSeconds)",
            ("actor_component", "Tick") =>
                "void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)",
            ("actor", "EndPlay") or ("actor_component", "EndPlay") =>
                "void EndPlay(const EEndPlayReason::Type EndPlayReason)",
            ("world_subsystem", "Initialize") or ("game_instance_subsystem", "Initialize") =>
                "void Initialize(FSubsystemCollectionBase& Collection)",
            ("world_subsystem", "Tick") => "void Tick(float DeltaSeconds)",
            ("world_subsystem", "Deinitialize") or ("game_instance_subsystem", "Deinitialize") =>
                "void Deinitialize()",
            _ => throw new InvalidOperationException(
                $"Unsupported lifecycle function '{kind}.{lifecycleName}'."),
        };
    }

    private static string RenderSuperCall(string kind, UeFunctionManifestEntry function)
    {
        return RenderSuperCall(kind, function.Name);
    }

    private static string RenderSuperCall(string kind, string lifecycleName)
    {
        return (kind, lifecycleName) switch
        {
            ("actor", "BeginPlay") or ("actor_component", "BeginPlay") => "Super::BeginPlay();",
            ("actor", "Tick") => "Super::Tick(DeltaSeconds);",
            ("actor_component", "Tick") => "Super::TickComponent(DeltaTime, TickType, ThisTickFunction);",
            ("actor", "EndPlay") or ("actor_component", "EndPlay") => "Super::EndPlay(EndPlayReason);",
            ("world_subsystem", "Initialize") or ("game_instance_subsystem", "Initialize") =>
                "Super::Initialize(Collection);",
            ("world_subsystem", "Tick") => "Super::Tick(DeltaSeconds);",
            ("world_subsystem", "Deinitialize") or ("game_instance_subsystem", "Deinitialize") =>
                "Super::Deinitialize();",
            _ => throw new InvalidOperationException(
                $"Unsupported lifecycle function '{kind}.{lifecycleName}'."),
        };
    }

    private static string[] GetHostLifecycleNames(string kind)
    {
        return kind switch
        {
            "actor" or "actor_component" => new[] { "BeginPlay", "EndPlay" },
            "world_subsystem" or "game_instance_subsystem" =>
                new[] { "Initialize", "Deinitialize" },
            _ => Array.Empty<string>(),
        };
    }

    private static bool IsActivationLifecycle(string lifecycleName) =>
        lifecycleName is "BeginPlay" or "Initialize";

    private static bool IsDeactivationLifecycle(string lifecycleName) =>
        lifecycleName is "EndPlay" or "Deinitialize";

    private static string RenderSignature(UeFunctionManifestEntry function, string name, bool includeVirtual)
    {
        return (includeVirtual ? "virtual " : string.Empty) + function.ReturnCppType + " " + name
            + "(" + RenderParameters(function.Parameters) + ")";
    }

    private static string RenderParameters(IReadOnlyList<UeFunctionParameterEntry> parameters)
    {
        return string.Join(", ", parameters.Select(parameter => parameter.CppType + " " + parameter.Name));
    }

    private static bool IsGeneratedImplementation(UeFunctionManifestEntry function)
    {
        return function.Flags.Contains("blueprint_native_event")
            || function.Flags.Contains("server")
            || function.Flags.Contains("client")
            || function.Flags.Contains("net_multicast");
    }

    private static bool NeedsConstructor(UeTypeManifestEntry type)
    {
        return type.Properties.Any(property => property.Initializer is not null)
            || HasScheduledTick(type)
            || HasNetworkContract(type);
    }

    private static bool HasNetworkContract(UeTypeManifestEntry type)
    {
        return type.Kind is "actor" or "actor_component"
            && (type.Properties.Any(property => property.Flags.Contains("replicated"))
                || type.Functions.Any(function => function.Flags.Any(flag =>
                    flag is "server" or "client" or "net_multicast")));
    }

    private static bool HasScheduledTick(UeTypeManifestEntry type)
    {
        return type.Kind is "actor" or "actor_component"
            && type.Functions.Any(function =>
                function.Name == "Tick" && function.Flags.Contains("lifecycle"));
    }

    private static string RenderClassFlags(IReadOnlyList<string> flags)
    {
        return string.Join(", ", flags.Select(flag => flag switch
        {
            "blueprintable" => "Blueprintable",
            "blueprint_type" => "BlueprintType",
            "abstract" => "Abstract",
            "not_placeable" => "NotPlaceable",
            "transient" => "Transient",
            _ => throw new InvalidOperationException($"Unsupported UCLASS flag '{flag}'."),
        }));
    }

    private static string RenderPropertyFlags(UePropertyManifestEntry property)
    {
        List<string> specifiers = property.Flags.Select(flag => flag switch
        {
            "edit_anywhere" => "EditAnywhere",
            "visible_anywhere" => "VisibleAnywhere",
            "blueprint_read_only" => "BlueprintReadOnly",
            "blueprint_read_write" => "BlueprintReadWrite",
            "replicated" when property.ReplicatedUsing.Length > 0 => "ReplicatedUsing=" + property.ReplicatedUsing,
            "replicated" => "Replicated",
            "save_game" => "SaveGame",
            "transient" => "Transient",
            _ => throw new InvalidOperationException($"Unsupported UPROPERTY flag '{flag}'."),
        }).ToList();
        if (property.Category.Length > 0)
        {
            specifiers.Add("Category=\"" + Escape(property.Category) + "\"");
        }
        return string.Join(", ", specifiers);
    }

    private static string RenderFunctionFlags(UeFunctionManifestEntry function)
    {
        List<string> specifiers = function.Flags
            .Where(flag => flag is not ("lifecycle" or "override"))
            .Select(flag => flag switch
            {
                "blueprint_callable" => "BlueprintCallable",
                "blueprint_pure" => "BlueprintPure",
                "blueprint_native_event" => "BlueprintNativeEvent",
                "blueprint_implementable_event" => "BlueprintImplementableEvent",
                "server" => "Server",
                "client" => "Client",
                "net_multicast" => "NetMulticast",
                "reliable" => "Reliable",
                "unreliable" => "Unreliable",
                _ => throw new InvalidOperationException($"Unsupported UFUNCTION flag '{flag}'."),
            }).ToList();
        if (function.Category.Length > 0)
        {
            specifiers.Add("Category=\"" + Escape(function.Category) + "\"");
        }
        return string.Join(", ", specifiers);
    }

    private static IReadOnlyList<UeTypeManifestEntry> TopologicalOrder(IReadOnlyList<UeTypeManifestEntry> types)
    {
        Dictionary<string, UeTypeManifestEntry> byCppName = types.ToDictionary(
            type => type.CppName,
            StringComparer.Ordinal);
        List<UeTypeManifestEntry> ordered = new(types.Count);
        HashSet<string> visiting = new(StringComparer.Ordinal);
        HashSet<string> visited = new(StringComparer.Ordinal);
        foreach (UeTypeManifestEntry type in types.OrderBy(type => type.TypeOrdinal))
        {
            Visit(type, byCppName, visiting, visited, ordered);
        }
        return ordered;
    }

    private static void Visit(
        UeTypeManifestEntry type,
        IReadOnlyDictionary<string, UeTypeManifestEntry> byCppName,
        ISet<string> visiting,
        ISet<string> visited,
        ICollection<UeTypeManifestEntry> ordered)
    {
        if (visited.Contains(type.CppName))
        {
            return;
        }
        if (!visiting.Add(type.CppName))
        {
            throw new InvalidOperationException($"Generated UE shell inheritance is cyclic at '{type.CppName}'.");
        }
        if (byCppName.TryGetValue(type.BaseCppName, out UeTypeManifestEntry? parent))
        {
            Visit(parent, byCppName, visiting, visited, ordered);
        }
        visiting.Remove(type.CppName);
        visited.Add(type.CppName);
        ordered.Add(type);
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
    }

    private static string RenderInitializer(SemanticUePropertyInitializer initializer)
    {
        string value = initializer.CanonicalValue;
        return initializer.Kind switch
        {
            "bool" or "int32" => value,
            "uint8" => "static_cast<uint8>(" + value + ")",
            "int8" => "static_cast<int8>(" + value + ")",
            "int16" => "static_cast<int16>(" + value + ")",
            "uint16" => "static_cast<uint16>(" + value + ")",
            "uint32" => value + "U",
            "int64" => value + "LL",
            "uint64" => value + "ULL",
            "float32" => EnsureFloatingPoint(value) + "f",
            "float64" => EnsureFloatingPoint(value),
            "string" => "TEXT(\"" + Escape(value) + "\")",
            _ => throw new InvalidOperationException(
                $"Unsupported UE property initializer kind '{initializer.Kind}'."),
        };
    }

    private static string EnsureFloatingPoint(string value)
    {
        return value.IndexOfAny(new[] { '.', 'E', 'e' }) >= 0 ? value : value + ".0";
    }

    private static string Normalize(StringBuilder output)
    {
        return output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }
}
