using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AvidScript.UeTypeGenerator;

internal static class UhtShellRenderer
{
    public const string HeaderPath = "Public/AvidScriptGeneratedTypes.h";
    public const string SourcePath = "Private/AvidScriptGeneratedTypes.cpp";

    public static string RenderHeader(string moduleName, IReadOnlyList<UeTypeManifestEntry> types)
    {
        StringBuilder output = new();
        output.AppendLine("// Generated by AvidScript.UeTypeGenerator. Do not edit.");
        output.AppendLine("#pragma once");
        output.AppendLine();
        output.AppendLine("#include \"CoreMinimal.h\"");
        output.AppendLine("#include \"Components/ActorComponent.h\"");
        output.AppendLine("#include \"GameFramework/Actor.h\"");
        output.AppendLine("#include \"Subsystems/GameInstanceSubsystem.h\"");
        output.AppendLine("#include \"Subsystems/WorldSubsystem.h\"");
        output.AppendLine("#include \"AvidScriptGeneratedTypes.generated.h\"");
        output.AppendLine();

        string apiMacro = moduleName.ToUpperInvariant() + "_API";
        foreach (UeTypeManifestEntry type in TopologicalOrder(types))
        {
            output.Append("UCLASS(").Append(RenderClassFlags(type.Flags)).AppendLine(")");
            output.Append("class ").Append(apiMacro).Append(' ').Append(type.CppName)
                .Append(" : public ").AppendLine(type.BaseCppName);
            output.AppendLine("{");
            output.AppendLine("    GENERATED_BODY()");
            output.AppendLine();
            output.AppendLine("public:");
            foreach (UePropertyManifestEntry property in type.Properties)
            {
                output.Append("    UPROPERTY(").Append(RenderPropertyFlags(property)).AppendLine(")");
                output.Append("    ").Append(property.CppType).Append(' ').Append(property.Name).AppendLine(";");
                output.AppendLine();
            }
            foreach (UeFunctionManifestEntry function in type.Functions.Where(function =>
                !function.Flags.Contains("lifecycle")))
            {
                AppendFunctionDeclaration(output, function);
            }
            if (type.Properties.Any(property => property.Flags.Contains("replicated")))
            {
                output.AppendLine("    virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;");
                output.AppendLine();
            }

            UeFunctionManifestEntry[] lifecycleFunctions = type.Functions
                .Where(function => function.Flags.Contains("lifecycle"))
                .ToArray();
            if (lifecycleFunctions.Length > 0 || type.Kind == "world_subsystem")
            {
                output.AppendLine("protected:");
                foreach (UeFunctionManifestEntry function in lifecycleFunctions)
                {
                    output.Append("    ").AppendLine(RenderLifecycleDeclaration(type.Kind, function));
                }
                if (type.Kind == "world_subsystem")
                {
                    output.AppendLine("    virtual TStatId GetStatId() const override;");
                }
                output.AppendLine();
            }
            output.AppendLine("};");
            output.AppendLine();
        }
        return Normalize(output);
    }

    public static string RenderSource(IReadOnlyList<UeTypeManifestEntry> types)
    {
        StringBuilder output = new();
        output.AppendLine("// Generated by AvidScript.UeTypeGenerator. Do not edit.");
        output.AppendLine("#include \"AvidScriptGeneratedTypes.h\"");
        output.AppendLine();
        output.AppendLine("#include \"Net/UnrealNetwork.h\"");
        output.AppendLine("#include \"ScriptTypes/AvidScriptGeneratedTypeDispatcher.h\"");
        output.AppendLine();

        foreach (UeTypeManifestEntry type in TopologicalOrder(types))
        {
            foreach (UeFunctionManifestEntry function in type.Functions)
            {
                if (function.Flags.Contains("blueprint_implementable_event"))
                {
                    continue;
                }
                AppendFunctionDefinition(output, type, function);
            }
            if (type.Properties.Any(property => property.Flags.Contains("replicated")))
            {
                output.Append("void ").Append(type.CppName)
                    .AppendLine("::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const");
                output.AppendLine("{");
                output.AppendLine("    Super::GetLifetimeReplicatedProps(OutLifetimeProps);");
                foreach (UePropertyManifestEntry property in type.Properties.Where(property =>
                    property.Flags.Contains("replicated")))
                {
                    output.Append("    DOREPLIFETIME(").Append(type.CppName).Append(", ")
                        .Append(property.Name).AppendLine(");");
                }
                output.AppendLine("}");
                output.AppendLine();
            }
            if (type.Kind == "world_subsystem")
            {
                output.Append("TStatId ").Append(type.CppName).AppendLine("::GetStatId() const");
                output.AppendLine("{");
                output.Append("    RETURN_QUICK_DECLARE_CYCLE_STAT(").Append(type.CppName)
                    .AppendLine(", STATGROUP_Tickables);");
                output.AppendLine("}");
                output.AppendLine();
            }
        }
        return Normalize(output);
    }

    private static void AppendFunctionDeclaration(StringBuilder output, UeFunctionManifestEntry function)
    {
        bool isOverride = function.Flags.Contains("override");
        bool generatedImplementation = IsGeneratedImplementation(function);
        if (!isOverride)
        {
            output.Append("    UFUNCTION(").Append(RenderFunctionFlags(function)).AppendLine(")");
        }
        if (generatedImplementation)
        {
            if (!isOverride)
            {
                output.Append("    ").Append(RenderSignature(function, function.Name, false)).AppendLine(";");
            }
            output.Append("    virtual ").Append(RenderSignature(function, function.Name + "_Implementation", false))
                .Append(isOverride ? " override;" : ";").AppendLine();
        }
        else
        {
            output.Append("    virtual ").Append(RenderSignature(function, function.Name, false));
            if (isOverride)
            {
                output.Append(" override");
            }
            output.AppendLine(";");
        }
        output.AppendLine();
    }

    private static void AppendFunctionDefinition(
        StringBuilder output,
        UeTypeManifestEntry type,
        UeFunctionManifestEntry function)
    {
        if (function.Flags.Contains("lifecycle"))
        {
            AppendLifecycleDefinition(output, type, function);
            return;
        }

        string nativeName = IsGeneratedImplementation(function)
            ? function.Name + "_Implementation"
            : function.Name;
        output.Append(function.ReturnCppType).Append(' ').Append(type.CppName).Append("::")
            .Append(nativeName).Append('(').Append(RenderParameters(function.Parameters)).AppendLine(")");
        output.AppendLine("{");
        AppendDispatchBody(output, type, function, function.Parameters.Select(parameter => parameter.Name).ToArray());
        output.AppendLine("}");
        output.AppendLine();
    }

    private static void AppendLifecycleDefinition(
        StringBuilder output,
        UeTypeManifestEntry type,
        UeFunctionManifestEntry function)
    {
        string definition = RenderLifecycleDefinition(type, function);
        output.AppendLine(definition);
        output.AppendLine("{");
        bool dispatchBeforeSuper = function.Name is "EndPlay" or "Deinitialize";
        if (!dispatchBeforeSuper)
        {
            output.Append("    ").AppendLine(RenderSuperCall(type.Kind, function));
        }
        string[] arguments = function.Name == "Tick"
            ? new[] { type.Kind == "actor_component" ? "DeltaTime" : "DeltaSeconds" }
            : Array.Empty<string>();
        AppendDispatchBody(output, type, function, arguments);
        if (dispatchBeforeSuper)
        {
            output.Append("    ").AppendLine(RenderSuperCall(type.Kind, function));
        }
        output.AppendLine("}");
        output.AppendLine();
    }

    private static void AppendDispatchBody(
        StringBuilder output,
        UeTypeManifestEntry type,
        UeFunctionManifestEntry function,
        IReadOnlyList<string> arguments)
    {
        if (arguments.Count > 0)
        {
            output.AppendLine("    FAvidScriptGeneratedCallArgument Arguments[] =");
            output.AppendLine("    {");
            foreach (string argument in arguments)
            {
                output.Append("        { &").Append(argument).AppendLine(" },");
            }
            output.AppendLine("    };");
        }
        if (function.ReturnCppType != "void")
        {
            output.Append("    ").Append(function.ReturnCppType).AppendLine(" Result{};");
        }
        output.AppendLine("    FAvidScriptGeneratedTypeDispatcher::Invoke(");
        output.AppendLine("        this,");
        output.Append("        ").Append(type.TypeOrdinal).AppendLine("u,");
        output.Append("        ").Append(function.MemberOrdinal).AppendLine("u,");
        output.Append("        ").Append(arguments.Count == 0
            ? "TConstArrayView<FAvidScriptGeneratedCallArgument>()"
            : "MakeArrayView(Arguments)").AppendLine(",");
        output.Append("        ").Append(function.ReturnCppType == "void" ? "nullptr" : "&Result").AppendLine(");");
        if (function.ReturnCppType != "void")
        {
            output.AppendLine("    return Result;");
        }
    }

    private static string RenderLifecycleDeclaration(string kind, UeFunctionManifestEntry function)
    {
        return "virtual " + RenderLifecycleSignature(kind, function) + " override;";
    }

    private static string RenderLifecycleDefinition(UeTypeManifestEntry type, UeFunctionManifestEntry function)
    {
        string signature = RenderLifecycleSignature(type.Kind, function);
        int nameOffset = signature.IndexOf(function.NativeName, StringComparison.Ordinal);
        return signature.Insert(nameOffset, type.CppName + "::");
    }

    private static string RenderLifecycleSignature(string kind, UeFunctionManifestEntry function)
    {
        return (kind, function.Name) switch
        {
            ("actor", "BeginPlay") or ("actor_component", "BeginPlay") => "void BeginPlay()",
            ("actor", "Tick") => "void Tick(float DeltaSeconds)",
            ("actor_component", "Tick") =>
                "void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)",
            ("actor", "EndPlay") or ("actor_component", "EndPlay") =>
                "void EndPlay(const EEndPlayReason::Type EndPlayReason)",
            ("world_subsystem", "Initialize") or ("game_instance_subsystem", "Initialize") =>
                "void Initialize(FSubsystemCollectionBase& Collection)",
            ("world_subsystem", "Tick") => "void Tick(float DeltaSeconds)",
            ("world_subsystem", "Deinitialize") or ("game_instance_subsystem", "Deinitialize") =>
                "void Deinitialize()",
            _ => throw new InvalidOperationException(
                $"Unsupported lifecycle function '{kind}.{function.Name}'."),
        };
    }

    private static string RenderSuperCall(string kind, UeFunctionManifestEntry function)
    {
        return (kind, function.Name) switch
        {
            ("actor", "BeginPlay") or ("actor_component", "BeginPlay") => "Super::BeginPlay();",
            ("actor", "Tick") => "Super::Tick(DeltaSeconds);",
            ("actor_component", "Tick") => "Super::TickComponent(DeltaTime, TickType, ThisTickFunction);",
            ("actor", "EndPlay") or ("actor_component", "EndPlay") => "Super::EndPlay(EndPlayReason);",
            ("world_subsystem", "Initialize") or ("game_instance_subsystem", "Initialize") =>
                "Super::Initialize(Collection);",
            ("world_subsystem", "Tick") => "Super::Tick(DeltaSeconds);",
            ("world_subsystem", "Deinitialize") or ("game_instance_subsystem", "Deinitialize") =>
                "Super::Deinitialize();",
            _ => throw new InvalidOperationException(
                $"Unsupported lifecycle function '{kind}.{function.Name}'."),
        };
    }

    private static string RenderSignature(UeFunctionManifestEntry function, string name, bool includeVirtual)
    {
        return (includeVirtual ? "virtual " : string.Empty) + function.ReturnCppType + " " + name
            + "(" + RenderParameters(function.Parameters) + ")";
    }

    private static string RenderParameters(IReadOnlyList<UeFunctionParameterEntry> parameters)
    {
        return string.Join(", ", parameters.Select(parameter => parameter.CppType + " " + parameter.Name));
    }

    private static bool IsGeneratedImplementation(UeFunctionManifestEntry function)
    {
        return function.Flags.Contains("blueprint_native_event")
            || function.Flags.Contains("server")
            || function.Flags.Contains("client")
            || function.Flags.Contains("net_multicast");
    }

    private static string RenderClassFlags(IReadOnlyList<string> flags)
    {
        return string.Join(", ", flags.Select(flag => flag switch
        {
            "blueprintable" => "Blueprintable",
            "blueprint_type" => "BlueprintType",
            "abstract" => "Abstract",
            "not_placeable" => "NotPlaceable",
            "transient" => "Transient",
            _ => throw new InvalidOperationException($"Unsupported UCLASS flag '{flag}'."),
        }));
    }

    private static string RenderPropertyFlags(UePropertyManifestEntry property)
    {
        List<string> specifiers = property.Flags.Select(flag => flag switch
        {
            "edit_anywhere" => "EditAnywhere",
            "visible_anywhere" => "VisibleAnywhere",
            "blueprint_read_only" => "BlueprintReadOnly",
            "blueprint_read_write" => "BlueprintReadWrite",
            "replicated" when property.ReplicatedUsing.Length > 0 => "ReplicatedUsing=" + property.ReplicatedUsing,
            "replicated" => "Replicated",
            "save_game" => "SaveGame",
            "transient" => "Transient",
            _ => throw new InvalidOperationException($"Unsupported UPROPERTY flag '{flag}'."),
        }).ToList();
        if (property.Category.Length > 0)
        {
            specifiers.Add("Category=\"" + Escape(property.Category) + "\"");
        }
        return string.Join(", ", specifiers);
    }

    private static string RenderFunctionFlags(UeFunctionManifestEntry function)
    {
        List<string> specifiers = function.Flags
            .Where(flag => flag is not ("lifecycle" or "override"))
            .Select(flag => flag switch
            {
                "blueprint_callable" => "BlueprintCallable",
                "blueprint_pure" => "BlueprintPure",
                "blueprint_native_event" => "BlueprintNativeEvent",
                "blueprint_implementable_event" => "BlueprintImplementableEvent",
                "server" => "Server",
                "client" => "Client",
                "net_multicast" => "NetMulticast",
                "reliable" => "Reliable",
                "unreliable" => "Unreliable",
                _ => throw new InvalidOperationException($"Unsupported UFUNCTION flag '{flag}'."),
            }).ToList();
        if (function.Category.Length > 0)
        {
            specifiers.Add("Category=\"" + Escape(function.Category) + "\"");
        }
        return string.Join(", ", specifiers);
    }

    private static IReadOnlyList<UeTypeManifestEntry> TopologicalOrder(IReadOnlyList<UeTypeManifestEntry> types)
    {
        Dictionary<string, UeTypeManifestEntry> byCppName = types.ToDictionary(
            type => type.CppName,
            StringComparer.Ordinal);
        List<UeTypeManifestEntry> ordered = new(types.Count);
        HashSet<string> visiting = new(StringComparer.Ordinal);
        HashSet<string> visited = new(StringComparer.Ordinal);
        foreach (UeTypeManifestEntry type in types.OrderBy(type => type.TypeOrdinal))
        {
            Visit(type, byCppName, visiting, visited, ordered);
        }
        return ordered;
    }

    private static void Visit(
        UeTypeManifestEntry type,
        IReadOnlyDictionary<string, UeTypeManifestEntry> byCppName,
        ISet<string> visiting,
        ISet<string> visited,
        ICollection<UeTypeManifestEntry> ordered)
    {
        if (visited.Contains(type.CppName))
        {
            return;
        }
        if (!visiting.Add(type.CppName))
        {
            throw new InvalidOperationException($"Generated UE shell inheritance is cyclic at '{type.CppName}'.");
        }
        if (byCppName.TryGetValue(type.BaseCppName, out UeTypeManifestEntry? parent))
        {
            Visit(parent, byCppName, visiting, visited, ordered);
        }
        visiting.Remove(type.CppName);
        visited.Add(type.CppName);
        ordered.Add(type);
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static string Normalize(StringBuilder output)
    {
        return output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }
}
