#include "BindingGeneration/AvidScriptEditorCSharpUeTypeDeclarationRenderer.h"

void FAvidScriptEditorCSharpUeTypeDeclarationRenderer::AppendReferenceSurface(TArray<FString>& OutLines)
{
	OutLines.Append({
		TEXT("[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]"),
		TEXT("public sealed class UClassAttribute : Attribute"),
		TEXT("{"),
		TEXT("    public string Name { get; set; } = string.Empty;"),
		TEXT("    public bool Blueprintable { get; set; } = true;"),
		TEXT("    public bool BlueprintType { get; set; } = true;"),
		TEXT("    public bool Abstract { get; set; }"),
		TEXT("    public bool NotPlaceable { get; set; }"),
		TEXT("    public bool Transient { get; set; }"),
		TEXT("}"),
		TEXT(""),
		TEXT("[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, Inherited = false, AllowMultiple = false)]"),
		TEXT("public sealed class UPropertyAttribute : Attribute"),
		TEXT("{"),
		TEXT("    public bool EditAnywhere { get; set; }"),
		TEXT("    public bool VisibleAnywhere { get; set; }"),
		TEXT("    public bool BlueprintReadOnly { get; set; }"),
		TEXT("    public bool BlueprintReadWrite { get; set; }"),
		TEXT("    public bool Replicated { get; set; }"),
		TEXT("    public string ReplicatedUsing { get; set; } = string.Empty;"),
		TEXT("    public bool SaveGame { get; set; }"),
		TEXT("    public bool Transient { get; set; }"),
		TEXT("    public string Category { get; set; } = string.Empty;"),
		TEXT("}"),
		TEXT(""),
		TEXT("[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]"),
		TEXT("public sealed class UFunctionAttribute : Attribute"),
		TEXT("{"),
		TEXT("    public bool BlueprintCallable { get; set; }"),
		TEXT("    public bool BlueprintPure { get; set; }"),
		TEXT("    public bool BlueprintNativeEvent { get; set; }"),
		TEXT("    public bool BlueprintImplementableEvent { get; set; }"),
		TEXT("    public bool Server { get; set; }"),
		TEXT("    public bool Client { get; set; }"),
		TEXT("    public bool NetMulticast { get; set; }"),
		TEXT("    public bool Reliable { get; set; }"),
		TEXT("    public bool Unreliable { get; set; }"),
		TEXT("    public string Category { get; set; } = string.Empty;"),
		TEXT("}"),
		TEXT(""),
		TEXT("public abstract class AvidActor"),
		TEXT("{"),
		TEXT("    protected virtual void BeginPlay() { }"),
		TEXT("    protected virtual void Tick(float deltaSeconds) { }"),
		TEXT("    protected virtual void EndPlay() { }"),
		TEXT("}"),
		TEXT(""),
		TEXT("public abstract class AvidActorComponent"),
		TEXT("{"),
		TEXT("    protected virtual void BeginPlay() { }"),
		TEXT("    protected virtual void Tick(float deltaSeconds) { }"),
		TEXT("    protected virtual void EndPlay() { }"),
		TEXT("}"),
		TEXT(""),
		TEXT("public abstract class AvidWorldSubsystem"),
		TEXT("{"),
		TEXT("    protected virtual void Initialize() { }"),
		TEXT("    protected virtual void Tick(float deltaSeconds) { }"),
		TEXT("    protected virtual void Deinitialize() { }"),
		TEXT("}"),
		TEXT(""),
		TEXT("public abstract class AvidGameInstanceSubsystem"),
		TEXT("{"),
		TEXT("    protected virtual void Initialize() { }"),
		TEXT("    protected virtual void Deinitialize() { }"),
		TEXT("}"),
		TEXT("")
	});
}
